- index.js
- readme.md
- test.js
Does it make sense to `return` it anywhere else? Maybe in `.render()` and `.clear()` in case you want to do something like this (for some reason):
```js
const ora = require('ora')
const spinner = ora('Loading unicorns')
.render()
.render()
.render()
.clear()
.start();
```
Fixes #10.
> Make the API chainable

- .travis.yml
- package.json
- test.js
- use the the `stream` option instead of hooking stderr
- remove hook-std, it's not needed anymore
I'm using this approach on [my project that uses Ora](https://github.com/josmardias/bike-vitoria/blob/master/src/loading-spinner-test.js)
> Use the stream option instead of hooking stderr - fixes #1 

- index.js
- readme.md
- test.js
Closes #19. Just took a jab at it. Not sure about a few things.
Firstly to check if the passed object is a promise I'm using
```
typeof action.then === 'function'
```
I read somewhere that I'm supposed to use 
```
Promise.resolve(action) === action
```
but for some reason it does not work when I run the test.
Also I'm not sure about the thoroughness of my tests or the way im waiting for the promises.
I also know that in general when a promise rejects it's recommended to use a `.catch()` rather than the second parameter to `.then()`, but for some reason this fails in the test case as apparently the stream gets closed before the `.catch()` executes.
> Add `.promise()` method

- index.js
- readme.md
- test.js
Makes it more convenient to set a new past-tense message when stopping. 
(Partial implementation of #28)
> Add ability to change text when stopping and persisting

- index.js
- readme.md
- test.js
Added an optional argument to `start` to set the text before starting. I find this very useful with the following pattern:
```js
const spinner = ora()
try {
spinner.start('Thing a')
await thingA()
spinner.succeed()
spinner.start('Thing b')
await thingB()
spinner.succeed()
// ...
} catch (err) {
spinner.fail(err.toString())
}
```
> Add text option to start function

- readme.md
The way it's documented right now, under the `Instance` heading, is quite confusing. It seems to imply I can do this:
```
const spinner = ora('Doing stuff');
spinner.promise(somePromise);
// => Unhandled rejection TypeError: spinner.promise is not a function
```
I had to go read the source code to realize it's not an instance method.
I saw that it was originally documented as `ora.promise` until 85551fb59586d516386214ba098de15af2a1410b. I believe it's better to leave it that way.
Alternatively, you could provide an example.
> Clarify `.promise` usage

- readme.md
This PR adds `halo` to `related` section. Thanks for being the inspiration for this package. 😸
> Add halo to the Related section in the readme

- index.js
- test.js
When running succeed (or fail) the text was outputted even if spinner was not enabled.
> Make `stopAnPersist()` not run if spinner is not enabled

- .travis.yml
- index.js
- package.json
- readme.md
- test.js
Count how many rows are taken up by the spinner and the text and clear the appropriate number of lines. Fix clear() so it doesn't clear *further* lines until render() is called again.
Fixes #38. Fixes #7.
Add hideCursor option. Fixes #27. Users may still hide the cursor outside of Ora.
There aren't any tests for hiding the cursor so I didn't add one for not hiding it either.
---
I did a quick test in the Windows command prompt and the wrap handling seemed to work fine.
> Handle wrapping, add hideCursor option

- index.js
- readme.md
- test.js
Thought about expanding `isSpinning` to be
```js
return this.enabled && this.id !== null;
```
since it can't be spinning if it's not enabled, but wasn't sure about the implications. That would simplify the check in `start()` to be `if (this.isSpinning)`
> Add `.isSpinning` property

- .travis.yml
- index.js
- package.json
- test.js
To fix CI failures
- Remove Node 4:
```javascript
const {input, flags: opts} = cli;
^
```
- Add Node 10
- Improve code for XO be happy (Use object destructuring)
> Require Node.js 6

- index.js
moveCursor, clearLine, etc are not methods that every stream will have. Only streams that are specifically TTY streams.
I think by default this.stream is set to process.stderr. In unix it's very possible for stderr to not be a TTY.
When running some node thing in the background (with `concurrently`), I got an exception.
> Don't call stream TTY methods on streams that are not TTYs

- readme.md
I was looking for a spinner implementation in Go and found this package.
Happily, you have a `related` section in the README, but there was no Go package.
This PR adds two spinner packages for the Go programing language into the related section in the README.
Thanks for writing this lib :)
> Add two spinner packages for Go to the Related section in the readme

- index.d.ts
- index.js
- index.test-d.ts
- readme.md
- test.js
> Add `prefixText` option

- index.js
This appears to be a typo, and was leading to this behavior:
```javascript
const spinner = new ora('Testing').start();
setTimeout(() => spinner.succeed('Completed'), 2000);
```
```
✔ Completedn[~/Development/ora-test (master)]$
```
> Fix regression with `stopAndPersist` output

- index.d.ts
- index.js
- readme.md
- test.js
> Hide `prefixText` when it's an empty string

- example.js
- index.d.ts
- index.js
- index.test-d.ts
- readme.md
Add consumeStdin option, fixes #97
Though I have no idea how to write tests for it.
Plus, if some other library decides to something like what we do here, but won't be as careful as we are, things might get ugly. But that's mostly limitation of node's way of handling things.
> Discard stdin by default

- index.js
- test.js
> Set the correct interval when changing spinner by name

- index.js
Fixes #130
This fixes the problem for now.
Multiple spinners do work and readline run in parallel works too.
But I think it wasn't broken before(when I implemented original feature) and I suspect there were some changes in nodejs code base.Need to check further to find out why exactly it is working like that now(and readline related hack with 'keypress' shouldn't be there ideally).
> Fix handling of Ctrl+C on spinners beyond first one

- example.js
- index.d.ts
- index.js
- package.json
- readme.md
Disable `discardStdin` option on Windows. BTW, when using `cmd` nothing is printed anyway on Windows(unless in raw mode I suppose). Fixes #132, fixes #134, fixes #136.
Problem mostly boiled down to using raw mode twice(on separate ticks) hanged the problem under windows. Relevant change added to `example.js`(tested in `cmd`).
Make discarding work with multiple parallel `ora` instances, fixes #133.
#134 is a problem under macs too, looking into it right now.
> Fix `discardStdin` option

- readme.md
Hello there! 
A couple of months ago I developed [Spinnies](https://www.npmjs.com/package/spinnies), a Node.js module to create and manage multiple spinners in command-line interface programs. This PR adds a link and a brief description of the library in the [Related](https://github.com/sindresorhus/ora#related) section in the readme.md file.
> Add Spinnies to the list of related projects

- index.js
I'm using next.js and it use Ora to show building spinner.
However, on Travis CI, there is extra `- undefined` message because of undefined text.
```
- undefined
> Using external babel configuration
- undefined
> Location: "/xxxxxxxxxxxxx/babel.config.json"
- undefined
> Using external babel configuration
- undefined
> Location: "/xxxxxxxxxxxxx/.babelrc.js"
- undefined
Creating an optimized production build
Compiled successfully.
```
After this PR:
```
> Using external babel configuration
> Location: "/xxxxxxxxxxxxx/babel.config.json"
> Using external babel configuration
> Location: "/xxxxxxxxxxxxx/.babelrc.js"
Creating an optimized production build
Compiled successfully.
```
> Fix undefined text on disabled Ora

- index.d.ts
- index.js
- index.test-d.ts
- readme.md
- test.js
This adds the possibility to prepend a timestamp on the log.
> Allow setting `prefixText` dynamically

- index.d.ts
- index.js
- index.test-d.ts
- readme.md
- test.js
Implements `isSilent` as discussed in #147.
Fixes #147
> Add `isSilent` option

- index.js
- package.json
mute-stream is abandoned, which uses legacy streams. 
Bl is a modern replacement.
Fixes #162
> Use `bl` package instead of `mute-stream`

- index.js
Best guess of whether win32-based platforms support Unicode in the console
Fixes #159
> Use nice spinner on VSCode's terminal and Windows Terminal

- index.js
- test.js
Hello 👋 
Thank you for this great tool ❤️ 
I spotted this bug while working on https://github.com/netlify/cli/pull/2576.
Currently `'default'` passes the validation while not being a valid spinner name.
> Don't allow `default` as a spinner

- index.d.ts
- index.js
- index.test-d.ts
- package.json
- readme.md
- test.js
Implemented https://github.com/sindresorhus/ora/issues/169#issuecomment-873269524
Improves ora.promise:
1) The action can now be a function. It will automatically be executed. The corresponding spinner will be used as argument to that function.
2) It will now return a promise, that resolves when ora.promise given promise/function is resolved, so the user can `await ora.promise(..)`.
3) Added successText and failText, that will be used in the spinner.succeed()/spinner.fail(). They can be either a string or a function. Being a function, successText will receive as argument the return of the action resolve, and failText will receive the action reject content.
Fixes #169
> Improve `ora.promise()`

- utilities.js
Patches the close in `StdinDiscarder` to keep stdin unpaused if it was already in that state. `readline.close()` has the undocumented side-effect of pausing the input stream, in this case `stdin`.
Fixes #209.
> Close readline in `StdinDiscarder` without changing stdin's pause state

- index.d.ts
- index.js
- index.test-d.ts
- readme.md
- test.js
Closes #217.
Reexports `cliSpinners` as `spinners` and adds to types (with test), updates a test, and documents in the readme.
> Export `cliSpinners` as `spinners`

- example.js
- index.d.ts
- index.js
- index.test-d.ts
- readme.md
- test.js
Closes #212.
Adds support for a `suffixText` option/field on a given spinner, and on the `stopAndPersist` method. Includes docs, types, and tests.
> Add `suffixText` option

- package.json
`ora@7.0.0` uses the `string-width` package, but doesn't include it as a dependency or peer-dependency.
Users that install & import the latest version of `ora` for the first time will run into the following runtime error if `string-width` isn't specifically listed as a dependency or required by any other dependencies.
```bash
node:internal/modules/cjs/loader:1077
const err = new Error(message);
^
Error: Cannot find module 'string-width'
...
```
This error is caused by Line 7 in `node_modules/ora/index.js`
```js
import stringWidth from "string-width";
```
Add `string-width` as a dependency or peer-dependency in ora's `package.json`.
```package.json
{
"name": "ora",
...
"dependencies": {
...
"string-width": "^6.1.0"
}
}
```
- Mac OS X Ventura
- Debian Linux 12 Bookworm
- Node v18.7.0
- Node …
> Added string-width to dependencies

- index.d.ts
- readme.md
color property of class Ora can be a boolean `false` when the default color and chalk color application will not occur, but the type hint only mentions `Color` whereas it should be `Color | boolean`.
> Add support for `boolean` value for `color` option
